- name: Exercise for setting up a web server in an EC 
  # hosts: ubuntu
  # Use the public IP if the VM is already created
  hosts: 34.238.244.241
  user: ec2-user
  become: true
  become_method: sudo
  become_user: root