version: 2.1


jobs:
   configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["0f:85:02:a0:03:01:fa:a3:43:ee:81:25:55:de:41:c8"] # You can get this ID in the section where you registered the SSH Key
      - run:
          name: Install dependencies
          command: |
            # install the dependencies needed for your playbook
            yum install pip
            python -m pip install --upgrade pip
            pip install --user ansible 
      - run:
          name: Configure server
          command: |
            ansible-playbook -i inventory.txt main.yml

  
workflows:
  
  my_Workflow:
    jobs:
      - configure_infrastructure
      