version: 2.1


jobs:
  create_infrastructure:  
      
      docker:
        - image: amazon/aws-cli
           
          environment:
              
            AWS_ACCESS_KEY_ID: AKIAZ2P3QK7AQDSFY2EB
            AWS_SECRET_ACCESS_KEY: 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
            AWS_DEFAULT_REGION: us-east-1          
          

                      
      steps:
        - checkout # check out the code in the project directory
        - run:
            name : Create Infrastructure Stack
            command: |
              
              aws cloudformation deploy  --template-file template.yml  --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} --region us-east-1


  
workflows:
  
  my_Workflow:
    jobs:
      - create_infrastructure
      