version: 2.1


jobs:
  delete_infrastructure:  
      
      docker:
        - image: amazon/aws-cli

          environment:
              
            AWS_ACCESS_KEY_ID: AKIAZ2P3QK7A5LTSNYEC
            AWS_SECRET_ACCESS_KEY: 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
            AWS_DEFAULT_REGION: us-east-1
                      
      steps:
        - checkout # check out the code in the project directory
        - run:
            name : Delete Infrastructure Stack
            command: |
              
              aws cloudformation delete-stack --stack-name myStack-1fcf7 
              


workflows:
  
  my_Workflow:
    jobs:
      - delete_infrastructure