version: 2.1


jobs:
  create_infrastructure:  
      
      docker:
        - image: amazon/aws-cli


                      
      steps:
        - checkout # check out the code in the project directory
        - run:
            name : Create Infrastructure Stack
            command: |
              
              aws cloudformation deploy  --template-file template.yml  --stack-name myStack-123 --region us-east-1
              


workflows:
  
  my_Workflow:
    jobs:
      - create_infrastructure